// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Wind

#ifndef _WIND_UI_H
#define _WIND_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Wind.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_compassglow_png);   // assets/CompassGlow.png
LV_IMG_DECLARE( ui_img_portstarboardcolours_png);   // assets/PortStarBoardColours.png
LV_IMG_DECLARE( ui_img_truepointer_png);   // assets/TruePointer.png
LV_IMG_DECLARE( ui_img_apparantpointer_png);   // assets/ApparantPointer.png

// FONTS
LV_FONT_DECLARE( ui_font_CodePro60);
LV_FONT_DECLARE( ui_font_CodePro70);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
