// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Wind

#include "../ui.h"

// COMPONENT DataBox

lv_obj_t *ui_DataBox_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_DataBox;
cui_DataBox = lv_obj_create(comp_parent);
lv_obj_set_width( cui_DataBox, 180);
lv_obj_set_height( cui_DataBox, 118);
lv_obj_set_align( cui_DataBox, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( cui_DataBox, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_DataBox, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_DataBox, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_DataBox, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_DataBox, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(cui_DataBox, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DBValue;
cui_DBValue = lv_label_create(cui_DataBox);
lv_obj_set_width( cui_DBValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_DBValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_DBValue, 0 );
lv_obj_set_y( cui_DBValue, 15 );
lv_obj_set_align( cui_DBValue, LV_ALIGN_TOP_MID );
lv_label_set_text(cui_DBValue,"35");
lv_obj_set_style_text_color(cui_DBValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_DBValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_DBValue, &ui_font_CodePro70, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DBLabel;
cui_DBLabel = lv_label_create(cui_DataBox);
lv_obj_set_width( cui_DBLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_DBLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_DBLabel, 0 );
lv_obj_set_y( cui_DBLabel, -10 );
lv_obj_set_align( cui_DBLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(cui_DBLabel,"TWS");
lv_obj_set_style_text_color(cui_DBLabel, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_DBLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DBUnit;
cui_DBUnit = lv_label_create(cui_DataBox);
lv_obj_set_width( cui_DBUnit, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_DBUnit, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_DBUnit, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(cui_DBUnit,"Kts");
lv_obj_set_style_text_color(cui_DBUnit, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(cui_DBUnit, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_DATABOX_NUM);
children[UI_COMP_DATABOX_DATABOX] = cui_DataBox;
children[UI_COMP_DATABOX_DBVALUE] = cui_DBValue;
children[UI_COMP_DATABOX_DBLABEL] = cui_DBLabel;
children[UI_COMP_DATABOX_DBUNIT] = cui_DBUnit;
lv_obj_add_event_cb(cui_DataBox, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_DataBox, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_DataBox_create_hook(cui_DataBox);
return cui_DataBox; 
}

