// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Wind

#ifndef _UI_COMP_DATABOX_H
#define _UI_COMP_DATABOX_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT DataBox
#define UI_COMP_DATABOX_DATABOX 0
#define UI_COMP_DATABOX_DBVALUE 1
#define UI_COMP_DATABOX_DBLABEL 2
#define UI_COMP_DATABOX_DBUNIT 3
#define _UI_COMP_DATABOX_NUM 4
lv_obj_t *ui_DataBox_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
