// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Wind

#include "../ui.h"

void ui_comp_DataBox_create_hook( lv_obj_t * comp)
{
}
