// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Wind

#ifndef UI_WIND_H
#define UI_WIND_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Wind
extern void ui_Wind_screen_init(void);
extern void ui_Wind_screen_destroy(void);
extern lv_obj_t *ui_Wind;
extern lv_obj_t *ui_Compass;
extern lv_obj_t *ui_CompassRose;
extern lv_obj_t *ui_Colours;
extern lv_obj_t *ui_Heading;
extern lv_obj_t *ui_CentreWindSpeed;
extern lv_obj_t *ui_WindSpeedLabel;
extern lv_obj_t *ui_AWS;
extern lv_obj_t *ui_CentreKnots;
extern lv_obj_t *ui_CentreWindAngle;
extern lv_obj_t *ui_WindAngleLabel;
extern lv_obj_t *ui_AWA;
extern lv_obj_t *ui_Deg;
extern lv_obj_t *ui_TruePointer;
extern lv_obj_t *ui_ApparantPointer;
extern lv_obj_t *ui_RHS1;
extern lv_obj_t *ui_RHS2;
extern lv_obj_t *ui_RHS3;
extern lv_obj_t *ui_RHS4;
extern lv_obj_t *ui_RHS5;
extern lv_obj_t *ui_LHS1;
extern lv_obj_t *ui_LHS2;
extern lv_obj_t *ui_LHS3;
extern lv_obj_t *ui_LHS4;
extern lv_obj_t *ui_LHS5;
// CUSTOM VARIABLES
extern lv_obj_t *uic_CompassRose;
extern lv_obj_t *uic_Heading;
extern lv_obj_t *uic_AWS;
extern lv_obj_t *uic_AWA;
extern lv_obj_t *uic_TruePointer;
extern lv_obj_t *uic_ApparantPointer;
extern lv_obj_t *uic_RHS1;
extern lv_obj_t *uic_DBValue;
extern lv_obj_t *uic_RHS1_DBLabel;
extern lv_obj_t *uic_RHS1_DBUnit;
extern lv_obj_t *uic_RHS2;
extern lv_obj_t *uic_RHS2_DBValue;
extern lv_obj_t *uic_RHS2_DBLabel;
extern lv_obj_t *uic_RHS2_DBUnit;
extern lv_obj_t *uic_RHS3;
extern lv_obj_t *uic_RHS3_DBValue;
extern lv_obj_t *uic_RHS3_DBLabel;
extern lv_obj_t *uic_RHS3_DBUnit;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

