// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Wind

#include "../ui.h"

lv_obj_t *uic_RHS3_DBUnit;
lv_obj_t *uic_RHS3_DBLabel;
lv_obj_t *uic_RHS3_DBValue;
lv_obj_t *uic_RHS3;
lv_obj_t *uic_RHS2_DBUnit;
lv_obj_t *uic_RHS2_DBLabel;
lv_obj_t *uic_RHS2_DBValue;
lv_obj_t *uic_RHS2;
lv_obj_t *uic_RHS1_DBUnit;
lv_obj_t *uic_RHS1_DBLabel;
lv_obj_t *uic_DBValue;
lv_obj_t *uic_RHS1;
lv_obj_t *uic_ApparantPointer;
lv_obj_t *uic_TruePointer;
lv_obj_t *uic_AWA;
lv_obj_t *uic_AWS;
lv_obj_t *uic_Heading;
lv_obj_t *uic_CompassRose;
lv_obj_t *ui_Wind = NULL;lv_obj_t *ui_Compass = NULL;lv_obj_t *ui_CompassRose = NULL;lv_obj_t *ui_Colours = NULL;lv_obj_t *ui_Heading = NULL;lv_obj_t *ui_CentreWindSpeed = NULL;lv_obj_t *ui_WindSpeedLabel = NULL;lv_obj_t *ui_AWS = NULL;lv_obj_t *ui_CentreKnots = NULL;lv_obj_t *ui_CentreWindAngle = NULL;lv_obj_t *ui_WindAngleLabel = NULL;lv_obj_t *ui_AWA = NULL;lv_obj_t *ui_Deg = NULL;lv_obj_t *ui_TruePointer = NULL;lv_obj_t *ui_ApparantPointer = NULL;lv_obj_t *ui_RHS1 = NULL;lv_obj_t *ui_RHS2 = NULL;lv_obj_t *ui_RHS3 = NULL;lv_obj_t *ui_RHS4 = NULL;lv_obj_t *ui_RHS5 = NULL;lv_obj_t *ui_LHS1 = NULL;lv_obj_t *ui_LHS2 = NULL;lv_obj_t *ui_LHS3 = NULL;lv_obj_t *ui_LHS4 = NULL;lv_obj_t *ui_LHS5 = NULL;
// event funtions

// build funtions

void ui_Wind_screen_init(void)
{
ui_Wind = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Wind, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_style_bg_color(ui_Wind, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Wind, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Compass = lv_obj_create(ui_Wind);
lv_obj_set_width( ui_Compass, 600);
lv_obj_set_height( ui_Compass, 600);
lv_obj_set_align( ui_Compass, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Compass, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Compass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Compass, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Compass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Compass, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CompassRose = lv_img_create(ui_Compass);
lv_img_set_src(ui_CompassRose, &ui_img_compassglow_png);
lv_obj_set_width( ui_CompassRose, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CompassRose, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CompassRose, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_CompassRose, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_CompassRose, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_CompassRose,100);

ui_Colours = lv_img_create(ui_Compass);
lv_img_set_src(ui_Colours, &ui_img_portstarboardcolours_png);
lv_obj_set_width( ui_Colours, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Colours, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Colours, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Colours, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Colours, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Heading = lv_label_create(ui_Compass);
lv_obj_set_width( ui_Heading, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Heading, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Heading, 0 );
lv_obj_set_y( ui_Heading, -260 );
lv_obj_set_align( ui_Heading, LV_ALIGN_CENTER );
lv_label_set_text(ui_Heading,"350");
lv_obj_set_style_text_font(ui_Heading, &lv_font_montserrat_38, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Heading, lv_color_hex(0xDCDCDC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Heading, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Heading, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Heading, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_Heading, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_Heading, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Heading, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Heading, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Heading, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Heading, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CentreWindSpeed = lv_obj_create(ui_Compass);
lv_obj_set_width( ui_CentreWindSpeed, 200);
lv_obj_set_height( ui_CentreWindSpeed, 100);
lv_obj_set_x( ui_CentreWindSpeed, 0 );
lv_obj_set_y( ui_CentreWindSpeed, -60 );
lv_obj_set_align( ui_CentreWindSpeed, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CentreWindSpeed, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CentreWindSpeed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CentreWindSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CentreWindSpeed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CentreWindSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WindSpeedLabel = lv_label_create(ui_CentreWindSpeed);
lv_obj_set_width( ui_WindSpeedLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WindSpeedLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WindSpeedLabel, 0 );
lv_obj_set_y( ui_WindSpeedLabel, -20 );
lv_obj_set_align( ui_WindSpeedLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_WindSpeedLabel,"AWS");
lv_obj_set_style_text_color(ui_WindSpeedLabel, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WindSpeedLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_WindSpeedLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WindSpeedLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AWS = lv_label_create(ui_CentreWindSpeed);
lv_obj_set_width( ui_AWS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AWS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AWS, 0 );
lv_obj_set_y( ui_AWS, 10 );
lv_obj_set_align( ui_AWS, LV_ALIGN_CENTER );
lv_label_set_text(ui_AWS,"25");
lv_obj_set_style_text_color(ui_AWS, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AWS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AWS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AWS, &ui_font_CodePro70, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CentreKnots = lv_label_create(ui_CentreWindSpeed);
lv_obj_set_width( ui_CentreKnots, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CentreKnots, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CentreKnots, 70 );
lv_obj_set_y( ui_CentreKnots, 25 );
lv_obj_set_align( ui_CentreKnots, LV_ALIGN_CENTER );
lv_label_set_text(ui_CentreKnots,"Kts");
lv_obj_set_style_text_color(ui_CentreKnots, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_CentreKnots, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_CentreKnots, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CentreWindAngle = lv_obj_create(ui_Compass);
lv_obj_set_width( ui_CentreWindAngle, 140);
lv_obj_set_height( ui_CentreWindAngle, 80);
lv_obj_set_x( ui_CentreWindAngle, 0 );
lv_obj_set_y( ui_CentreWindAngle, 40 );
lv_obj_set_align( ui_CentreWindAngle, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CentreWindAngle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_CentreWindAngle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_CentreWindAngle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_CentreWindAngle, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_CentreWindAngle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WindAngleLabel = lv_label_create(ui_CentreWindAngle);
lv_obj_set_width( ui_WindAngleLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WindAngleLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WindAngleLabel, 0 );
lv_obj_set_y( ui_WindAngleLabel, -20 );
lv_obj_set_align( ui_WindAngleLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_WindAngleLabel,"AWA");
lv_obj_set_style_text_color(ui_WindAngleLabel, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_WindAngleLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_WindAngleLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_WindAngleLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AWA = lv_label_create(ui_CentreWindAngle);
lv_obj_set_width( ui_AWA, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AWA, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AWA, -5 );
lv_obj_set_y( ui_AWA, 25 );
lv_obj_set_align( ui_AWA, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_AWA,"S 70");
lv_obj_set_style_text_color(ui_AWA, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AWA, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AWA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AWA, &ui_font_CodePro60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Deg = lv_label_create(ui_CentreWindAngle);
lv_obj_set_width( ui_Deg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Deg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Deg, 20 );
lv_obj_set_y( ui_Deg, -5 );
lv_obj_set_align( ui_Deg, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_Deg,"o");
lv_obj_set_style_text_color(ui_Deg, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Deg, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TruePointer = lv_img_create(ui_Compass);
lv_img_set_src(ui_TruePointer, &ui_img_truepointer_png);
lv_obj_set_width( ui_TruePointer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TruePointer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TruePointer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TruePointer, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TruePointer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_TruePointer,950);

ui_ApparantPointer = lv_img_create(ui_Compass);
lv_img_set_src(ui_ApparantPointer, &ui_img_apparantpointer_png);
lv_obj_set_width( ui_ApparantPointer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ApparantPointer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ApparantPointer, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ApparantPointer, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ApparantPointer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_ApparantPointer,350);

ui_RHS1 = ui_DataBox_create(ui_Wind);
lv_obj_set_x( ui_RHS1, 0 );
lv_obj_set_y( ui_RHS1, 0 );

ui_RHS2 = ui_DataBox_create(ui_Wind);
lv_obj_set_x( ui_RHS2, 0 );
lv_obj_set_y( ui_RHS2, 120 );

ui_RHS3 = ui_DataBox_create(ui_Wind);
lv_obj_set_x( ui_RHS3, 0 );
lv_obj_set_y( ui_RHS3, 240 );

ui_RHS4 = ui_DataBox_create(ui_Wind);
lv_obj_set_x( ui_RHS4, 0 );
lv_obj_set_y( ui_RHS4, 360 );

ui_RHS5 = ui_DataBox_create(ui_Wind);
lv_obj_set_x( ui_RHS5, 0 );
lv_obj_set_y( ui_RHS5, 480 );

ui_LHS1 = ui_DataBox_create(ui_Wind);
lv_obj_set_x( ui_LHS1, 0 );
lv_obj_set_y( ui_LHS1, 0 );
lv_obj_set_align( ui_LHS1, LV_ALIGN_TOP_LEFT );

ui_LHS2 = ui_DataBox_create(ui_Wind);
lv_obj_set_x( ui_LHS2, 0 );
lv_obj_set_y( ui_LHS2, 240 );
lv_obj_set_align( ui_LHS2, LV_ALIGN_TOP_LEFT );

ui_LHS3 = ui_DataBox_create(ui_Wind);
lv_obj_set_x( ui_LHS3, 0 );
lv_obj_set_y( ui_LHS3, 120 );
lv_obj_set_align( ui_LHS3, LV_ALIGN_TOP_LEFT );

ui_LHS4 = ui_DataBox_create(ui_Wind);
lv_obj_set_x( ui_LHS4, 0 );
lv_obj_set_y( ui_LHS4, 360 );
lv_obj_set_align( ui_LHS4, LV_ALIGN_TOP_LEFT );

ui_LHS5 = ui_DataBox_create(ui_Wind);
lv_obj_set_x( ui_LHS5, 0 );
lv_obj_set_y( ui_LHS5, 480 );
lv_obj_set_align( ui_LHS5, LV_ALIGN_TOP_LEFT );

uic_CompassRose = ui_CompassRose;
uic_Heading = ui_Heading;
uic_AWS = ui_AWS;
uic_AWA = ui_AWA;
uic_TruePointer = ui_TruePointer;
uic_ApparantPointer = ui_ApparantPointer;
uic_RHS1 = ui_RHS1;
uic_DBValue = ui_comp_get_child(ui_RHS1, UI_COMP_DATABOX_DBVALUE);
uic_RHS1_DBLabel = ui_comp_get_child(ui_RHS1, UI_COMP_DATABOX_DBLABEL);
uic_RHS1_DBUnit = ui_comp_get_child(ui_RHS1, UI_COMP_DATABOX_DBUNIT);
uic_RHS2 = ui_RHS2;
uic_RHS2_DBValue = ui_comp_get_child(ui_RHS2, UI_COMP_DATABOX_DBVALUE);
uic_RHS2_DBLabel = ui_comp_get_child(ui_RHS2, UI_COMP_DATABOX_DBLABEL);
uic_RHS2_DBUnit = ui_comp_get_child(ui_RHS2, UI_COMP_DATABOX_DBUNIT);
uic_RHS3 = ui_RHS3;
uic_RHS3_DBValue = ui_comp_get_child(ui_RHS3, UI_COMP_DATABOX_DBVALUE);
uic_RHS3_DBLabel = ui_comp_get_child(ui_RHS3, UI_COMP_DATABOX_DBLABEL);
uic_RHS3_DBUnit = ui_comp_get_child(ui_RHS3, UI_COMP_DATABOX_DBUNIT);

}

void ui_Wind_screen_destroy(void)
{
   if (ui_Wind) lv_obj_del(ui_Wind);

// NULL screen variables
ui_Wind= NULL;
ui_Compass= NULL;
uic_CompassRose= NULL;
ui_CompassRose= NULL;
ui_Colours= NULL;
uic_Heading= NULL;
ui_Heading= NULL;
ui_CentreWindSpeed= NULL;
ui_WindSpeedLabel= NULL;
uic_AWS= NULL;
ui_AWS= NULL;
ui_CentreKnots= NULL;
ui_CentreWindAngle= NULL;
ui_WindAngleLabel= NULL;
uic_AWA= NULL;
ui_AWA= NULL;
ui_Deg= NULL;
uic_TruePointer= NULL;
ui_TruePointer= NULL;
uic_ApparantPointer= NULL;
ui_ApparantPointer= NULL;
uic_RHS1= NULL;
ui_RHS1= NULL;
uic_DBValue= NULL;
uic_RHS1_DBLabel= NULL;
uic_RHS1_DBUnit= NULL;
uic_RHS2= NULL;
ui_RHS2= NULL;
uic_RHS2_DBValue= NULL;
uic_RHS2_DBLabel= NULL;
uic_RHS2_DBUnit= NULL;
uic_RHS3= NULL;
ui_RHS3= NULL;
uic_RHS3_DBValue= NULL;
uic_RHS3_DBLabel= NULL;
uic_RHS3_DBUnit= NULL;
ui_RHS4= NULL;
ui_RHS5= NULL;
ui_LHS1= NULL;
ui_LHS2= NULL;
ui_LHS3= NULL;
ui_LHS4= NULL;
ui_LHS5= NULL;

}
